# Generated by Django 5.1.6 on 2025-02-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
