# Generated by Django 5.2 on 2025-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='2uqYE8uW', max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
