# Generated by Django 5.2 on 2025-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='89irkdsj', max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
