# Generated by Django 5.1.6 on 2025-02-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_brand_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
    ]
