# Generated by Django 5.1.6 on 2025-03-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='store_product',
        ),
        migrations.AddField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.store'),
        ),
    ]
