# Generated by Django 5.1.6 on 2025-03-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
