# Generated by Django 5.2.3 on 2025-07-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
