# Generated by Django 5.1.6 on 2025-03-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_brand_logo_url_category_logo_url_product_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
