# Generated by Django 5.2.3 on 2025-07-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_restriction',
            field=models.PositiveBigIntegerField(blank=True, help_text='Возрастное ограничение для товара', null=True, verbose_name='Возрастное ограничение'),
        ),
    ]
