# Generated by Django 5.1.6 on 2025-03-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
    ]
