# Generated by Django 5.2.3 on 2025-07-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='Product.brand', verbose_name='Бренд'),
        ),
    ]
