# Generated by Django 5.1.6 on 2025-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_brand_logo_url_remove_category_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/logos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/other/'),
        ),
    ]
