# Generated by Django 5.2.3 on 2025-07-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_alter_store_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(help_text='Для какого магазина эта категория', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Product.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(help_text='На каком складе находится товар', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Product.store', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(help_text='Какой вариант товара', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='Product.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(help_text='Товар, для которого изменялась цена', on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='Product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='store',
            field=models.ForeignKey(help_text='Склад, на котором изменялась цена', on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='Product.store', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(help_text='К какому складу/магазину относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.store', verbose_name='Склад/Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='В каких единицах измеряется товар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(help_text='Основной товар', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Product.store', verbose_name='Магазин/Склад'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='К какой категории относится', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Product.category', verbose_name='Категория'),
        ),
    ]
