# Generated by Django 5.2.3 on 2025-07-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_category_store_alter_inventory_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(help_text='К какой подкатегории относится', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Product.subcategory', verbose_name='Подкатегория'),
        ),
    ]
