# Generated by Django 5.1.6 on 2025-03-04 18:24

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/other/', validators=[Product.models.validate_image_size]),
        ),
    ]
