# Generated by Django 5.1.6 on 2025-03-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
    ]
