# Generated by Django 5.1.7 on 2025-03-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_rename_logo_brand_image_rename_logo_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='Product.storeproduct'),
        ),
    ]
