# Generated by Django 5.1.7 on 2025-03-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_quantity_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
    ]
