# Generated by Django 5.1.7 on 2025-03-16 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_remove_quantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-15 13:45:30.123456'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='Product.storeproduct'),
        ),
    ]
